config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :users

  #get 'stocks/show_industries'

#  devise_scope :user do 
#  	get 'valet/sign_up' => 'users/registrations#valet_new'
#  end

  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/filterable.rb
module Filterable
  extend ActiveSupport::Concern

  module ClassMethods
    def filter(filtering_params)
      results = self.where(nil)
      filtering_params.each do |key, value|
        results = results.public_send(key, value) if value.present?
      end
      results
    end
  end
end

app/models/stock.rb
class Stock < ApplicationRecord
	def self.icarus
		where('rank < ? AND mom > ?', 25,90)
	end

	def self.rising
		where('rank > ? AND mom > ?', 90,75)
	end

	def self.bargain
		where('rank > ? AND mom < ?', 90,30)
	end

	def self.caution
		where('rank < ? AND mom < ?', 25,10)
	end
	

	#def good?
	#	rank > 90 && mom > 70
	#end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

	

	enum user_type: [:client, :valet]
	after_initialize :set_default_user_type, :if => :new_record?
	def set_default_user_type
    	self.user_type ||= :client
  	end


  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :bikes
	has_many :jobs, foreign_key: :valet_id

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
  	jobs_path(@user)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = User.new
    end
end

app/controllers/stocks_controller.rb
require 'rest-client'
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]

  # GET /stocks
  # GET /stocks.json
  def index
    @stocks = Stock.all
    @icarus_stocks = Stock.icarus #Stock.all
    @rising_stocks = Stock.rising #Stock.all
    @bargain_stocks = Stock.bargain #Stock.all
    @caution_stocks = Stock.caution #Stock.all
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
    @stock = Stock.find(params[:id])
    ticker = @stock.symbol
    name = @stock.name
    @data = Quandl::Dataset.get('WIKI/' + ticker).data(params: { limit: 1 }).first
    @price_history = Quandl::Dataset.get('WIKI/' + ticker).data(params: { limit: 180})
    url = 'https://newsapi.org/v2/everything?q=' + name + '&from=2017-12-01&sortBy=popularity&apikey=d691cab4303d4289893580dedb78a770'
    @body = JSON.parse(RestClient.get(url))


     # render json: data.column_names

#      render json: data.data_fields

  end

  def show_industries
   @industry = Industry.find(params[:id])
  end


  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: 'Stock was successfully created.' }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1
  # PATCH/PUT /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: 'Stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_params
      params.require(:stock).permit(:symbol, :name, :industry, :rank, :mom)
    end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
 before_action :configure_permitted_parameters, if: :devise_controller?
  


  def valet_new
    @user = User.new user_type: :valet
    render :new
  end

  

  protected


  def after_sign_up_path_for(resource)
    edit_user_path(@user)
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :user_type) } 
  end




end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.new
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end



  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:fullname, :address, :phone_num, :user_type)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

def resource_name

:user

end

def resource

@resource ||= User.new

end

def devise_mapping

@devise_mapping ||= Devise.mappings[:user]

end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
 	<div class="fluid-container" style="margin-top: 70px">
      <div class="row">
        <div id="title">
        	<h1>Welcome to Market Madness</h1>
        	<h2><%= link_to "Sign up", "#sign_up", "data-toggle" => "modal"%> to receive our newsletter or <%= link_to "proceed to the madness", stocks_path %></h2>
        </div>
      </div>
    </div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to root_path, class: "navbar-brand" do %>
            Market Madness
          <% end %>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <%= yield :right_nav %>
              <% case current_user.user_type %>
                <% when 'client' %>
              <li><a href="/stocks">Stock Analysis</a></li>
              <% end %>

              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Settings", edit_user_registration_path %></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Sign Up", "#sign_up", "data-toggle" => "modal", :class => 'btn' %></li> 
              <li><%= link_to "Login", "#log_in", "data-toggle" => "modal", :class => 'btn' %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Valetbike</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script type="text/javascript"> $(function ()
          { $("#sign_up").modal({show:false });
    </script>
    <script type="text/javascript"> $(function ()
          { $("#log_in").modal({show:false });
    </script>

  </head>

  <body>
    <div id="reg_modals">
    <%= render template: "devise/sessions/new" %>
    <%= render template: "users/registrations/new" %>
    </div>
  	<%= render partial: "layouts/navbar" %>
  	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
          <%= yield %>
  </body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stock</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'welcome', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="fluid-container" style="margin-top: 70px">
      <div class="row">
        <div id="title">Stock</div>
        <div id="landing" class="col-sm-3">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/stocks/_form.html.erb
<%= form_with(model: stock, local: true) do |form| %>
  <% if stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% stock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<div id="stock-page">
  <div class="fluid-container">
      <div class="row">
        <div id="rising" class="col-xs-3" class="picks">
          <h3 style="color: rgba(30, 144, 255, 1); font-weight: bold;">Ride The Wave</h3>
            <div id="stock-list">
              <ul>
                <% @rising_stocks.each do |stock| %>
                  <li><%= link_to stock.symbol, stock_path(stock) %> - <%= link_to stock.name, stock_path(stock) %> <span style="color:rgba(30, 144, 255, 1);">[<%= stock.rank %>]</span></li>
                <% end %>
              </ul>
            </div>
        </div>

        <div id="icarus" class="col-xs-3" class="picks">
          <h3>Defying Gravity</h3>
          <div id="stock-list">
          <ul>
              <% @icarus_stocks.each do |stock| %>
                <li><%= link_to stock.symbol, stock_path(stock) %> - <%= link_to stock.name, stock_path(stock) %> <span style="color:yellow;">[<%= stock.rank %>]</span></li>
              <% end %>
            </ul>
          </div>
        </div>


        <div id="bargain" class="col-xs-3" class="picks">
          <h3 style="color: rgba(0, 255, 127, 1); font-weight: bold;">Bargain Bin</h3>
          <div id="stock-list">
          <ul>
              <% @bargain_stocks.each do |stock| %>
                <li><%= link_to stock.symbol, stock_path(stock) %> - <%= link_to stock.name, stock_path(stock) %> <span style="color: rgba(0, 255, 127, 1);">[<%= stock.rank %>]</span></li>
              <% end %>
            </ul>
          </div>
        </div>

        <div id="caution" class="col-xs-3" class="picks">
          <h3 style="color: red; font-weight: bold;">Look Out Below</h3>
          <div id="stock-list">
          <ul>
              <% @caution_stocks.each do |stock| %>
                <li><%= link_to stock.symbol, stock_path(stock) %> - <%= link_to stock.name, stock_path(stock) %> <span style="color:red;">[<%= stock.rank %>]</span></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/stocks/new.html.erb
<h1>New Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
<div id="stock-show">
  <div class="fluid-container">
      <div class="row">
        <div id="stock-details" class="col-xs-4">
          <h3>Stock Details</h3>
          <div id="stock-info">
            <p>
              <strong>Symbol: </strong>
              <%= @stock.symbol %>
            </p>

            <p>
              <strong>Name: </strong>
              <%= @stock.name %>
            </p>

            <p>
            <strong>Industry: </strong>
             <%= @stock.industry %>
            </p>
            <table>
              <thead>
                <tr>
                  <th>Score</th>
                  <th>PE</th>
                  <th>PB</th>
                  <th>PS</th>
                  <th>Dividend</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td><%= number_with_precision(@stock.rank, precision: 2) %></td>
                  <td><%= number_with_precision(@stock.pe, precision: 2) %></td>
                  <td><%= number_with_precision(@stock.pb, precision: 2) %></td>
                  <td><%= number_with_precision(@stock.ps, precision: 2) %></td>
                  <td><%= number_with_precision(@stock.div, precision: 2) %></td>
                </tr>
              </tbody>
            </table>

            Last Close: <%= @data.date %>
            <table>
              <thead>
                <tr>
                  <th>Close</th>
                  <th>High</th>
                  <th>Low</th>
                  <th>Volume</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td><%= number_with_precision(@data.close, precision: 2) %></td>
                  <td><%= number_with_precision(@data.high, precision: 2) %></td>
                  <td><%= number_with_precision(@data.low, precision: 2) %></td>
                  <td><%= number_with_precision(@data.volume, precision: 0, delimiter: ",") %></td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        

        <div id="stock-rank" class="col-xs-4">
          <h3>6 Month Price History</h3>
          <div id="price-history">
            
            <table>
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Close</th>
                  <th>Volume</th>
                </tr>
              </thead>
              <tbody>
                <% @price_history.each do |price| %>
                  <tr>
                    <td><%= price.date %></td>
                    <td><%= number_with_precision(price.close, precision: 2)%></td>
                    <td><%= number_with_precision(price.volume, precision: 0, delimiter: ",") %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>

        <div id="stock-rank" class="col-xs-4">
          <h3>Latest News</h3>
          <div id="news">
              <%#= @body["articles"] %>
              <% @body["articles"].each do |article| %>
              <li><%= link_to "#{article["title"]} (#{article["source"]["name"]})", article["url"] %></li>
              <% end %>
          </div>
        </div>


      </div>
    </div>
  </div>

  

  <%= link_to 'Back', stocks_path %>
</div>

app/views/stocks/show_industries.html.erb
<h1><%= @industry.name -%></h1>

<ul>
   <% @industry.stocks.each do |stock| %>
   <li><%= link_to stock.symbol, :action => "show", :id => stock.id -%></li>
   <% end %>
</ul>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fullname %></br>
    <%= form.text_field :fullname, id: :user_fullname %>
  </div>

  <div class="field">
    <%= form.label :address %></br>
    <%= form.text_field :address, id: :user_address %>
  </div>

  <div class="field">
    <%= form.label :phone_number %></br>
    <%= form.number_field :phone_num, id: :user_phone_num %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit %>
  </div>
  <br>
  <p><%= link_to "Click here", edit_user_registration_path %> to change your log in settings or delete your account</p>
    
<% end %>

app/views/users/edit.html.erb
<div id="details">
<h1>Account Details</h1>

<%= render 'form', user: @user %>

<%= link_to "Back", :back %>
</div>

app/views/users/index.html.erb
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Fullname</th>
      <th>Address</th>
      <th>Phone num</th>
      <th>User type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.fullname %></td>
        <td><%= user.address %></td>
        <td><%= user.phone_num %></td>
        <td><%= user.user_type %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fullname:</strong>
  <%= @user.fullname %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>Phone num:</strong>
  <%= @user.phone_num %>
</p>

<p>
  <strong>User type:</strong>
  <%= @user.user_type %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>